version: 0.0
os: linux

files:
  - source: / 
    destination: /var/www/html/

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: deploy_scripts/install.sh
      runas: root
  ApplicationStop:
    - location: deploy_scripts/stop.sh
      runas: root
  ApplicationStart:
    - location: deploy_scripts/start.sh
      runas: root
