version: 0.0
os: linux

files:
  - source: / 
    destination: /home/ubuntu/calculator

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: deploy_scripts/install.sh
      runas: ubuntu
  ApplicationStop:
    - location: deploy_scripts/stop.sh
      runas: ubuntu
  ApplicationStart:
    - location: deploy_scripts/start.sh
      runas: ubuntu
  ValidateService:
    - location: deploy_scripts/validate.sh
      runas: ubuntu
