version: 0.0
os: linux

files:
  - source: / 
    destination: /home/ec2-user/calculator

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: deploy_scripts/install.sh
      runas: ec2-user
      timeout: 300
  ApplicationStop:
    - location: deploy_scripts/stop.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: deploy_scripts/start.sh
      runas: ec2-user
      timeout: 300
  ValidateService:
    - location: deploy_scripts/validate.sh
      runas: ec2-user
